/*
 * File: app/store/ResultsStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SSClusterViewer.store.ResultsStore', {
    extend: 'Ext.data.Store',

    requires: [
        'SSClusterViewer.model.DayResult',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Array'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            model: 'SSClusterViewer.model.DayResult',
            storeId: 'ResultsStore',
            proxy: {
                type: 'ajax',
                url: '/ssdatarest-0.1.0/clusterresults',
                reader: {
                    type: 'array'
                }
            },
            listeners: {
                load: {
                    fn: me.onArraystoreLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onArraystoreLoad: function(store, records, successful, eOpts) {
        var datas = [];

        records.forEach(function(e){
            var tdate = e.raw.day;
            var year = tdate.substr(0,4);
            var month = tdate.substr(5,2);
            var day = tdate.substr(8,2);

            var dts = (Date.UTC(parseInt(year), parseInt(month)-1, parseInt(day))/1000).toString();
            var val = e.raw.clusterid;
            var row = {date: dts, value: val+1};
            datas.push(row);
        });

        console.log(datas);
        window.calDays.update(datas);
    }

});