/*
 * File: app/store/measureDimStore.js
 *
 * This file was generated by Sencha Architect version 3.0.4.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SSMeasureViewer.store.measureDimStore', {
    extend: 'Ext.data.Store',

    requires: [
        'SSMeasureViewer.model.MeasureDim'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'SSMeasureViewer.model.MeasureDim',
            storeId: 'measureDimStore',
            data: [
                {
                    measure: 'humidity',
                    mean: 52.17127318116976,
                    stddev: 38.010035664614755
                },
                {
                    measure: 'altitude',
                    mean: 27.996045736992812,
                    stddev: 72.81108826125575
                },
                {
                    measure: 'wind-speed',
                    mean: 5.90238165245516,
                    stddev: 14.092460107309252
                },
                {
                    measure: 'soil-moisture',
                    mean: 105.83757529697264,
                    stddev: 1470.9157335314683
                },
                {
                    measure: 'noise',
                    mean: 56.055003303933155,
                    stddev: 37.89365012832978
                },
                {
                    measure: 'co-index',
                    mean: 5.658878387309981,
                    stddev: 48.77563174139781
                },
                {
                    measure: 'parking',
                    mean: 0.0,
                    stddev: 19.012175585998055
                },
                {
                    measure: 'odometer',
                    mean: 39670.52307302725,
                    stddev: 50440.1330091922
                },
                {
                    measure: 'speed',
                    mean: 8.23556109628533,
                    stddev: 19.17337728327844
                },
                {
                    measure: 'temperature',
                    mean: 20.58494813076193,
                    stddev: 26.996048410984354
                },
                {
                    measure: 'atmospheric-pressure',
                    mean: 1018.4724414387905,
                    stddev: 999.6583444815876
                },
                {
                    measure: 'soil-temperature',
                    mean: 22.468404988513313,
                    stddev: 4.366468441583664
                },
                {
                    measure: 'count',
                    mean: 7.244696906179257,
                    stddev: 13.105432392482816
                },
                {
                    measure: 'occupancy',
                    mean: 6.443312651966126,
                    stddev: 15.935781351135653
                },
                {
                    measure: 'rainfall',
                    mean: 1.9602077820248947E-4,
                    stddev: 19.000740294495756
                },
                {
                    measure: 'solar-radiation',
                    mean: 56.61256199157113,
                    stddev: 120.68033809788939
                },
                {
                    measure: 'luminosity',
                    mean: 16764.482909980165,
                    stddev: 291345.0907211201
                },
                {
                    measure: 'course',
                    mean: 53.637512904922374,
                    stddev: 103.49033470163172
                },
                {
                    measure: 'particles',
                    mean: 0.500370675820256,
                    stddev: 18.502444409097414
                },
                {
                    measure: 'relative-humidity',
                    mean: 67.53398867413522,
                    stddev: 56.881995967644826
                }
            ]
        }, cfg)]);
    }
});